const InvoiceConstants = {
  CREATE_INVOICE: "CREATE_INVOICE",
  ADD_LINE_ITEM: "ADD_LINE_ITEM",
  SEND_INVOICE: "SEND_INVOICE",
  UPDATE_INVOICE: "UPDATE_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
};

export default InvoiceConstants;
